services:
  app:
    image: greenmelon5543/cdib:latest
    env_file:
      - ./.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: on-failure